<?php

class CoolSoftGalleryGalleryModuleFrontController extends ModuleFrontController
{
    public function initContent()
    {
       parent::initContent();

       $moduleImages = $this->imgUrls();
       $lang = $this->context->language->id;

       $this->context->smarty->assign(
            array(
              'custom_text1' => Configuration::get('CUSTOM_PAGE_TEXT1', $lang),
              'custom_text2' => Configuration::get('CUSTOM_PAGE_TEXT2', $lang),
              'gallery_images' => $moduleImages,
        ));

        $this->setTemplate("module:coolsoftgallery/views/templates/front/coolsoftgallery.tpl");
    }

    public function setMedia()
    {
        $this->registerStylesheet(
            "front-controller-mymodule",
            'modules/' . $this->module->name . '/views/templates/css/lightgallery.min.css',
            [
                'priority' => 999
            ]
        );
        $this->registerStylesheet(
            "front-controller-mymodule-custom",
            'modules/' . $this->module->name . '/views/templates/css/lightgallery-custom.css',
            [
                'priority' => 999
            ]
        );
        $this->registerJavascript(
            "front-controller-mymodule",
            'modules/' . $this->module->name . '/views/templates/js/lightgallery.min.js',
            [
                'position' => 'bottom',
                'priority' => 900,
            ]
        );
        $this->registerJavascript(
            "front-controller-mymodule-full",
            'modules/' . $this->module->name . '/views/templates/js/lg-fullscreen.min.js',
            [
                'position' => 'bottom',
                'priority' => 910,
            ]
        );
        $this->registerJavascript(
            "front-controller-mymodule-thumbnail",
            'modules/' . $this->module->name . '/views/templates/js/lg-thumbnail.min.js',
            [
                'position' => 'bottom',
                'priority' => 920,
            ]
        );
        $this->registerJavascript(
            "front-controller-mymodule-custom",
            'modules/' . $this->module->name . '/views/templates/js/customize-lightgallery.js',
            [
                'position' => 'bottom',
                'priority' => 999,
            ]
        );
        return parent::setMedia(); // TODO: Change the autogenerated stub
    }

    public function imgUrls()
    {


        $fileListAll = scandir(dirname(_PS_MODULE_DIR_).DIRECTORY_SEPARATOR.'modules'.DIRECTORY_SEPARATOR.'coolsoftgallery'.DIRECTORY_SEPARATOR.'img');
        $fileList = array_diff($fileListAll, array('.', '..'));

        $links = array();
        foreach($fileList as $filename){
            $links[] = "\modules\coolsoftgallery\img".DIRECTORY_SEPARATOR.$filename;
        }
        return $links;
    }

    public function getBreadcrumbLinks( ){

        $moduleBreadcrumb =  $this->l('CoolSoftGallery_breadcrumb');
        $breadcrumb = parent::getBreadcrumbLinks();
            $breadcrumb['links'][] = [
            'title' => $this->getTranslator()->trans($moduleBreadcrumb, [], 'Breadcrumb'),
            'url' => $this->context->link->getModuleLink('coolsoftgallery', 'gallery')
        ];

        return $breadcrumb;
    }
}